{
 "title": "Categories",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "year",
    "label": "Year",
    "query": "select distinct \"year\" from trend_summary;"
   },
   {
    "name": "category",
    "label": "Category",
    "query": "SELECT \n  id AS __value,\n  title AS __text\nFROM category"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 'Categories' AS title" }
   ]
  },
  {
   "title": "Categories",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  id AS \"Category ID\",\n  title AS \"Category Title\"\nFROM category\nWHERE id IN ($category)\nORDER BY Title"
    }
   ]
  },
  {
   "title": "Overall Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  SUM(\"viewCount\") AS \"Views\",\n  SUM(likes) AS \"Likes\",\n  SUM(dislikes) AS \"Dislikes\",\n  SUM(\"commentCount\") AS \"Comments\"\nFROM video_summary"
      }
     ]
    },
    {
     "title": "Top Categories With Most Videos",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  max_freq,\n  category.title\nFROM \n  into_values((SELECT mcv_agg(1, \"categoryId\") FROM video)) AS values\nJOIN category ON category.id = values.value\nORDER BY max_freq DESC\nLIMIT 6"
      }
     ]
    },
    {
     "title": "Top Categories With Most Videos",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT \n  category.title AS \"Category\",\n  COUNT(*) AS \"Videos Published\"\nFROM video, category\nWHERE \"categoryId\"=category.id\nGROUP BY \"Category\"\nORDER BY \"Videos Published\"  DESC\nLIMIT 10"
      }
     ]
    },
    {
     "title": "Top Viewed Categories",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  category.title,\n  SUM(\"viewCount\") AS \"Views\"\nFROM video, category\nWHERE \"categoryId\"=category.id\nGROUP BY category.id\nORDER BY \"Views\" DESC\nLIMIT 3\n"
      }
     ]
    },
    {
     "title": "Most Viewed Videos",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.title AS \"Video Title\", \n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\",\n      MAX(\"viewCount\") AS \"Views\"\n    FROM\n      video\n    GROUP BY video.id\n    ORDER BY MAX(\"viewCount\") DESC\n    LIMIT 3\n  )\nSELECT \n  most.\"Video Title\", \n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  category.id AS \"Category ID\",\n  most.\"Views\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\"\nORDER BY most.\"Views\" DESC"
      }
     ]
    },
    {
     "title": "Top Liked Categories",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  category.title,\n  SUM(\"likes\") AS \"Likes\"\nFROM video, category\nWHERE \"categoryId\"=category.id\nGROUP BY category.id\nORDER BY \"Likes\" DESC\nLIMIT 3"
      }
     ]
    },
    {
     "title": "Most Liked Videos",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.title AS \"Video Title\", \n      MAX(likes) AS \"Likes\",\n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\"\n    FROM\n      video\n    GROUP BY video.id\n    ORDER BY MAX(likes) DESC\n    LIMIT 3\n  )\nSELECT \n  most.\"Video Title\", \n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  category.id AS \"Category ID\",\n  most.\"Likes\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\"\nORDER BY most.\"Likes\" DESC"
      }
     ]
    },
    {
     "title": "Top Disliked Categories",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  category.title,\n  SUM(\"dislikes\") AS \"Dislikes\"\nFROM video, category\nWHERE \"categoryId\"=category.id\nGROUP BY category.id\nORDER BY \"Dislikes\" DESC\nLIMIT 3"
      }
     ]
    },
    {
     "title": "Most Disliked Videos",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.title AS \"Video Title\", \n      MAX(dislikes) AS \"Dislikes\",\n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\"\n    FROM\n      video\n    GROUP BY video.id\n    ORDER BY MAX(dislikes) DESC\n    LIMIT 3\n  )\nSELECT \n  most.\"Video Title\", \n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  category.id AS \"Category ID\",\n  most.\"Dislikes\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\"\nORDER BY most.\"Dislikes\" DESC"
      }
     ]
    },
    {
     "title": "Top Commented Categories",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  category.title,\n  SUM(\"commentCount\") AS \"Comments\"\nFROM video, category\nWHERE \"categoryId\"=category.id\nGROUP BY category.id\nORDER BY \"Comments\" DESC\nLIMIT 3"
      }
     ]
    },
    {
     "title": "Most Commented Videos",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.title AS \"Video Title\", \n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\",\n      MAX(\"commentCount\") AS \"Comments\"\n    FROM\n      video\n    GROUP BY video.id\n    ORDER BY MAX(\"commentCount\") DESC\n    LIMIT 3\n  )\nSELECT \n  most.\"Video Title\", \n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  category.id AS \"Category ID\",\n  most.\"Comments\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\"\nORDER BY most.\"Comments\" DESC"
      }
     ]
    }
   ]
  },
  { "title": "Per Year", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  $year AS \"Year\""
    },
    {
     "rawSql": "SELECT \n  SUM(\"videosPublished\") AS \"Videos Published\"\nFROM video_summary\nWHERE year = $year \nGROUP BY \"year\""
    },
    {
     "rawSql": "SELECT\n  SUM(\"trendsCount\") AS \"Trends\"\nFROM trend_summary\nWHERE year = $year \nGROUP BY \"year\""
    }
   ]
  },
  {
   "title": "Top Trending Occurrences Per Category",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "WITH most AS \n  (\n    SELECT\n      \"categoryId\",\n      COUNT(*) AS \"Trends\"\n    FROM trend\n    WHERE \n      EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year\n    GROUP BY \"categoryId\"\n    ORDER BY \"Trends\" DESC\n    LIMIT 10\n  )\nSELECT \n  category.title AS \"Category\",\n  most.\"Trends\"\nFROM \n  category, most\nWHERE \n  category.id = most.\"categoryId\"\nORDER BY \"Trends\" DESC"
    }
   ]
  }
 ]
}