{
 "title": "Channels",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "year",
    "label": "Year",
    "query": "select distinct \"year\" from trend_summary;"
   },
   {
    "name": "channel",
    "label": "Channel",
    "query": "SELECT \n  id AS __value,\n  title AS __text\nFROM channel"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 'Channels' AS title" }
   ]
  },
  {
   "title": "Channels",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  title AS \"Channel Title\",\n  id AS \"Channel ID\"\nFROM channel\nWHERE id IN($channel)\nORDER BY title ASC"
    }
   ]
  },
  {
   "title": "Overall Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  SUM(\"viewCount\") AS \"Views\",\n  SUM(likes) AS \"Likes\",\n  SUM(dislikes) AS \"Dislikes\",\n  SUM(\"commentCount\") AS \"Comments\"\nFROM video_summary"
      }
     ]
    },
    {
     "title": "Top Channels With Most Videos",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": " SELECT \n  title AS \"Channel\",\n  \"videosPublished\" AS \"Videos Published\"\nFROM \n  channel\nORDER BY \"Videos Published\" DESC\nLIMIT 3"
      }
     ]
    },
    {
     "title": "Top Viewed Channels",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\n  channel.title AS \"Channel\",\n  channel.id AS \"Channel ID\",\n  SUM(\"viewCount\") AS \"Views\"\nFROM video, channel\nWHERE \"channelId\"=channel.id\nGROUP BY channel.id\nORDER BY \"Views\" DESC\nLIMIT 3\n"
      }
     ]
    },
    {
     "title": "Top Liked Channels",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\n  channel.title AS \"Channel\",\n  channel.id AS \"Channel ID\",\n  SUM(likes) AS \"Likes\"\nFROM video, channel\nWHERE \"channelId\"=channel.id\nGROUP BY channel.id\nORDER BY \"Likes\" DESC\nLIMIT 3\n"
      }
     ]
    },
    {
     "title": "Top Disliked Channels",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\n  channel.title AS \"Channel\",\n  channel.id AS \"Channel ID\",\n  SUM(dislikes) AS \"Dislikes\"\nFROM video, channel\nWHERE \"channelId\"=channel.id\nGROUP BY channel.id\nORDER BY \"Dislikes\" DESC\nLIMIT 3\n"
      }
     ]
    },
    {
     "title": "Top Commented Channels",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\n  channel.title AS \"Channel\",\n  channel.id AS \"Channel ID\",\n  SUM(\"commentCount\") AS \"Comments\"\nFROM video, channel\nWHERE \"channelId\"=channel.id\nGROUP BY channel.id\nORDER BY \"Comments\" DESC\nLIMIT 3\n"
      }
     ]
    }
   ]
  },
  { "title": "Per Year", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  $year AS \"Year\""
    },
    {
     "rawSql": "SELECT \n  SUM(\"videosPublished\") AS \"Videos Published\"\nFROM video_summary\nWHERE year = $year \nGROUP BY \"year\"\nORDER BY year  DESC"
    },
    {
     "rawSql": "SELECT\n  COUNT(*) AS \"Trends\"\nFROM trend\nWHERE \n  EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year"
    }
   ]
  },
  {
   "title": "Top Trending Occurrences Per Channel",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "WITH most AS \n  (\n    SELECT\n      \"channelId\",\n      COUNT(*) AS \"Trends\"\n    FROM trend\n    WHERE \n      EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year\n    GROUP BY \"channelId\"\n    ORDER BY \"Trends\" DESC\n    LIMIT 10\n  )\nSELECT \n  channel.title AS \"Channel\",\n  most.\"Trends\"\nFROM \n  channel, most\nWHERE \n  channel.id = most.\"channelId\""
    }
   ]
  }
 ]
}