{
 "title": "Regions",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "year",
    "label": "Year",
    "query": "select distinct \"year\" from trend_summary;"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 'Regions' AS title" }
   ]
  },
  {
   "title": "Regions",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \n  id AS \"Region Code\",\n  name AS \"Region Name\"\nFROM region\nORDER BY name"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \n  id AS \"Region Code\",\n  name AS \"Region Name\"\nFROM region"
    }
   ]
  },
  {
   "title": "Overall Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distinct Categories, Channels and Videos",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(*) AS \"Categories\" FROM category "
      },
      {
       "rawSql": "SELECT COUNT(*) AS \"Channels\" FROM channel "
      },
      {
       "rawSql": "SELECT \n  SUM(\"videosPublished\") AS \"Videos\"\nFROM video_summary"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  SUM(\"viewCount\") AS \"Views\",\n  SUM(likes) AS \"Likes\",\n  SUM(dislikes) AS \"Dislikes\",\n  SUM(\"commentCount\") AS \"Comments\"\nFROM video_summary"
      }
     ]
    },
    {
     "title": "Views Per Day Of The Week",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\n  \"dowPublished\" AS \"Day\",\n  SUM(\"viewCount\") AS \"Views 2020\"\nFROM video\nWHERE \n  EXTRACT(YEAR FROM \"publishedAt\" AT TIME ZONE 'UTC') = 2020\nGROUP BY \"Day\"\nORDER BY 1\n"
      },
      {
       "rawSql": "SELECT\n  \"dowPublished\" AS \"Day\",\n  SUM(\"viewCount\") AS \"Views 2021\"\nFROM video\nWHERE \n  EXTRACT(YEAR FROM \"publishedAt\" AT TIME ZONE 'UTC') = 2021\nGROUP BY \"Day\"\nORDER BY 1\n"
      },
      {
       "rawSql": "SELECT\n  \"dowPublished\" AS \"Day\",\n  SUM(\"viewCount\") AS \"Views 2022\"\nFROM video\nWHERE \n  EXTRACT(YEAR FROM \"publishedAt\" AT TIME ZONE 'UTC') = 2022\nGROUP BY \"Day\"\nORDER BY 1\n"
      },
      {
       "rawSql": "SELECT\n  \"dowPublished\" AS \"Day\",\n  SUM(\"viewCount\") AS \"Views 2023\"\nFROM video\nWHERE \n  EXTRACT(YEAR FROM \"publishedAt\" AT TIME ZONE 'UTC') = 2023\nGROUP BY \"Day\"\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Videos Published Per Year",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT \n  year AS \"Year\",\n  SUM(\"videosPublished\") AS \"Videos Published\"\nFROM video_summary\nGROUP BY year\nORDER BY year  DESC"
      }
     ]
    },
    {
     "title": "Best Day Of The Week For Views",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  \"day\" AS \"Best Day\",\n  AVG(\"ViewCount\") AS \"Total Views\"\nFROM (\n  SELECT\n    \"dowPublished\" AS \"day\",\n    SUM(\"viewCount\") AS \"ViewCount\"\n  FROM video\n  WHERE \n    EXTRACT(YEAR FROM \"publishedAt\" AT TIME ZONE 'UTC') IN (2020,2021,2022,2023)\n  GROUP BY \"day\"\n  ORDER BY 1\n) AS perDOWperYear\nGROUP BY \"day\"\nORDER BY \"Total Views\" DESC\nLIMIT 1"
      }
     ]
    },
    {
     "title": "Views Per Number Of Videos Posted Per Channel",
     "type": "xychart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT  \n  statsPerChannel.\"Videos Per Channel\",\n  SUM(statsPerChannel.\"Views Per Channel\") AS \"Total Views\",\n  AVG(statsPerChannel.\"Views Per Channel\") AS \"Average Views\"\nFROM \n  (SELECT \n      COUNT(id) AS \"Videos Per Channel\",\n      SUM(\"viewCount\") AS \"Views Per Channel\"\n    FROM video\n    GROUP BY \"channelId\"\n  ) AS statsPerChannel\nGROUP BY statsPerChannel.\"Videos Per Channel\"\nORDER BY statsPerChannel.\"Videos Per Channel\" ASC"
      }
     ]
    },
    {
     "title": "Top Channels With Most Videos",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": " SELECT\n  title AS \"Channel\",\n  \"videosPublished\" AS \"Videos Published\"\nFROM \n  channel\nwhere \"videosPublished\" IS NOT NULL\nORDER BY \"Videos Published\" DESC\nLIMIT 10"
      }
     ]
    },
    {
     "title": "Top Categories With Most Videos",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  max_freq,\n  category.title\nFROM into_values((SELECT mcv_agg(1, \"categoryId\") FROM video)) AS values\nJOIN category ON category.id = values.value\nORDER BY max_freq DESC\nLIMIT 3"
      }
     ]
    },
    {
     "title": "Most Viewed Categories",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.\"categoryId\",\n      SUM(\"viewCount\") AS \"Views\"\n    FROM video\n    GROUP BY video.\"categoryId\"\n    ORDER BY SUM(\"viewCount\") DESC\n    LIMIT 3\n  )\nSELECT \n  category.title AS \"Category\",\n  category.id AS \"Category ID\",\n  most.\"Views\"\nFROM \n  category, most\nWHERE \n  category.id = most.\"categoryId\""
      }
     ]
    },
    {
     "title": "Most Viewed Channels",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.\"channelId\",\n      SUM(\"viewCount\") AS \"Views\"\n    FROM video\n    GROUP BY video.\"channelId\"\n    ORDER BY SUM(\"viewCount\") DESC\n    LIMIT 3\n  )\nSELECT \n  channel.title AS \"Channel\",\n  most.\"channelId\" AS \"Channel ID\",\n  most.\"Views\"\nFROM \n  channel, most\nWHERE \n  channel.id = most.\"channelId\"\nORDER BY most.\"Views\" DESC"
      }
     ]
    },
    {
     "title": "Most Viewed Videos",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.title AS \"Video Title\", \n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\",\n      MAX(\"viewCount\") AS \"Views\"\n    FROM\n      video\n    GROUP BY video.id\n    ORDER BY MAX(\"viewCount\") DESC\n    LIMIT 3\n  )\nSELECT \n  most.\"Video Title\", \n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  category.id AS \"Category ID\",\n  most.\"Views\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\"\nORDER BY most.\"Views\" DESC"
      }
     ]
    },
    {
     "title": "Most Liked Videos",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.title AS \"Video Title\", \n      MAX(likes) AS \"Likes\",\n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\"\n    FROM\n      video\n    GROUP BY video.id\n    ORDER BY MAX(likes) DESC\n    LIMIT 3\n  )\nSELECT \n  most.\"Video Title\", \n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  category.id AS \"Category ID\",\n  most.\"Likes\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\"\nORDER BY most.\"Likes\" DESC"
      }
     ]
    },
    {
     "title": "Most Disliked Videos",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.title AS \"Video Title\", \n      MAX(dislikes) AS \"Dislikes\",\n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\"\n    FROM\n      video\n    GROUP BY video.id\n    ORDER BY MAX(dislikes) DESC\n    LIMIT 3\n  )\nSELECT \n  most.\"Video Title\", \n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  category.id AS \"Category ID\",\n  most.\"Dislikes\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\"\nORDER BY most.\"Dislikes\" DESC"
      }
     ]
    },
    {
     "title": "Most Commented Videos",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.title AS \"Video Title\", \n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\",\n      MAX(\"commentCount\") AS \"Comments\"\n    FROM\n      video\n    GROUP BY video.id\n    ORDER BY MAX(\"commentCount\") DESC\n    LIMIT 3\n  )\nSELECT \n  most.\"Video Title\", \n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  category.id AS \"Category ID\",\n  most.\"Comments\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\"\nORDER BY most.\"Comments\" DESC"
      }
     ]
    }
   ]
  },
  { "title": "Per Year", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  $year AS \"Year\""
    },
    {
     "rawSql": "SELECT \n  SUM(\"videosPublished\") AS \"Videos Published\"\nFROM video_summary\nWHERE year = $year \nGROUP BY \"year\""
    },
    {
     "rawSql": "SELECT\n  SUM(\"trendsCount\") AS \"Trends\"\nFROM trend_summary\nWHERE year = $year \nGROUP BY \"year\""
    }
   ]
  },
  {
   "title": "Trending Categories Per Region",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"regionId\" AS \"Region\",\n  SUM(\"trendingCategories\") AS \"Categories\"\nFROM trend_summary\nWHERE year = $year \nGROUP BY \"regionId\"\nORDER BY \"Categories\" DESC"
    }
   ]
  },
  {
   "title": "Trending Videos Per Region",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"regionId\" AS \"Region\",\n  SUM(\"trendingVideos\") AS \"Videos\"\nFROM trend_summary\nWHERE year = $year \nGROUP BY \"regionId\"\nORDER BY \"Videos\" DESC"
    }
   ]
  },
  {
   "title": "Trending Channels Per Region",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"regionId\" AS \"Region\",\n  SUM(\"trendingChannels\") AS \"Channels\"\nFROM trend_summary\nWHERE year = $year \nGROUP BY \"regionId\"\nORDER BY \"Channels\" DESC"
    }
   ]
  },
  {
   "title": "Top Trending Occurrences Per Category",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "WITH most AS \n  (\n    SELECT\n      \"categoryId\",\n      COUNT(*) AS \"Trends\"\n    FROM trend\n    WHERE \n      EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year\n    GROUP BY \"categoryId\"\n    ORDER BY \"Trends\" DESC\n    LIMIT 10\n  )\nSELECT \n  category.title AS \"Category\",\n  most.\"Trends\"\nFROM \n  category, most\nWHERE \n  category.id = most.\"categoryId\"\nORDER BY \"Trends\" DESC"
    }
   ]
  },
  {
   "title": "Top Trending Occurrences Per Channel",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "WITH most AS \n  (\n    SELECT\n      \"channelId\",\n      COUNT(*) AS \"Trends\"\n    FROM trend\n    WHERE \n      EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year\n    GROUP BY \"channelId\"\n    ORDER BY \"Trends\" DESC\n    LIMIT 10\n  )\nSELECT \n  channel.title AS \"Channel\",\n  most.\"Trends\"\nFROM \n  channel, most\nWHERE \n  channel.id = most.\"channelId\""
    }
   ]
  },
  {
   "title": "Top Trending Occurrences Per Video",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "WITH most AS \n  (\n    SELECT\n      \"videoId\",\n      COUNT(*) AS \"Trends\"\n    FROM trend\n    WHERE \n      EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year\n    GROUP BY \"videoId\"\n    ORDER BY \"Trends\" DESC\n    LIMIT 10\n  )\nSELECT \n  video.title AS \"Video\",\n  most.\"Trends\"\nFROM \n  video, most\nWHERE \n  video.id = most.\"videoId\"\nORDER BY \"Trends\" DESC"
    }
   ]
  }
 ]
}