{
 "title": "Videos",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "year",
    "label": "Year",
    "query": "select distinct \"year\" from trend_summary;"
   },
   {
    "name": "channel",
    "label": "List Videos Of Channel",
    "query": "SELECT \n  id AS __value,\n  title AS __text\nFROM channel"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 'Videos' AS title" }
   ]
  },
  {
   "title": "Videos",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \n  id AS \"Video ID\",\n  title AS \"Video Title\"\nFROM video\nWHERE \"channelId\" IN ($channel)\nORDER BY title"
    }
   ]
  },
  {
   "title": "Overall Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Videos",
     "type": "stat",
     "gridPos": { "h": 4, "w": 10, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  SUM(\"videosPublished\") AS \"Videos\"\nFROM video_summary"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 14, "x": 10, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  SUM(\"viewCount\") AS \"Views\",\n  SUM(likes) AS \"Likes\",\n  SUM(dislikes) AS \"Dislikes\",\n  SUM(\"commentCount\") AS \"Comments\"\nFROM video_summary"
      }
     ]
    },
    {
     "title": "Best Day Of The Week To Publish Videos",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  \"day\" AS \"Best Day For Views\",\n  AVG(\"ViewCount\") AS \"Total Views\"\nFROM (\nSELECT\n  EXTRACT(DOW FROM \"publishedAt\") AS \"day\",\n  SUM(\"viewCount\") AS \"ViewCount\"\nFROM video\nWHERE \n  EXTRACT(YEAR FROM \"publishedAt\" AT TIME ZONE 'UTC') IN (2020,2021,2022,2023)\nGROUP BY \"day\"\nORDER BY 1\n) AS perDOWperYear\nGROUP BY \"day\"\nORDER BY \"Total Views\" DESC\nLIMIT 1"
      }
     ]
    },
    {
     "title": "Top Categories With Most Videos",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  max_freq,\n  category.title\nFROM into_values((SELECT mcv_agg(1, \"categoryId\") FROM video)) AS values\nJOIN category ON category.id = values.value\nORDER BY max_freq DESC\nLIMIT 3"
      }
     ]
    },
    {
     "title": "Views Per Day Of The Week",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\n  EXTRACT(DOW FROM \"publishedAt\") AS \"Day\",\n  SUM(\"viewCount\") AS \"Views 2020\"\nFROM video\nWHERE \n  EXTRACT(YEAR FROM \"publishedAt\" AT TIME ZONE 'UTC') = 2020\nGROUP BY \"Day\"\nORDER BY 1\n"
      },
      {
       "rawSql": "SELECT\n  EXTRACT(DOW FROM \"publishedAt\") AS \"Day\",\n  SUM(\"viewCount\") AS \"Views 2021\"\nFROM video\nWHERE \n  EXTRACT(YEAR FROM \"publishedAt\" AT TIME ZONE 'UTC') = 2021\nGROUP BY \"Day\"\nORDER BY 1\n"
      },
      {
       "rawSql": "SELECT\n  EXTRACT(DOW FROM \"publishedAt\") AS \"Day\",\n  SUM(\"viewCount\") AS \"Views 2022\"\nFROM video\nWHERE \n  EXTRACT(YEAR FROM \"publishedAt\" AT TIME ZONE 'UTC') = 2020\nGROUP BY \"Day\"\nORDER BY 1\n"
      },
      {
       "rawSql": "SELECT\n  EXTRACT(DOW FROM \"publishedAt\") AS \"Day\",\n  SUM(\"viewCount\") AS \"Views 2023\"\nFROM video\nWHERE \n  EXTRACT(YEAR FROM \"publishedAt\" AT TIME ZONE 'UTC') = 2023\nGROUP BY \"Day\"\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Videos Published Per Year",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT \n  year AS \"Year\",\n  SUM(\"videosPublished\") AS \"Videos Published\"\nFROM video_summary\nGROUP BY year\nORDER BY year  DESC"
      }
     ]
    },
    {
     "title": "Most Viewed Video",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.id AS \"Video ID\",\n      video.title AS \"Video Title\", \n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\",\n      MAX(\"viewCount\") AS \"Views\"\n    FROM\n      video\n    GROUP BY video.id\n    ORDER BY MAX(\"viewCount\") DESC\n    LIMIT 1\n  )\nSELECT \n  most.\"Video Title\",\n  most.\"Video ID\",\n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  most.\"Views\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\""
      }
     ]
    },
    {
     "title": "Most Liked Video",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.id AS \"Video ID\",\n      video.title AS \"Video Title\", \n      MAX(likes) AS \"Likes\",\n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\"\n    FROM\n      video\n    GROUP BY video.id\n    ORDER BY MAX(likes) DESC\n    LIMIT 1\n  )\nSELECT \n  most.\"Video Title\",\n  most.\"Video ID\", \n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  most.\"Likes\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\""
      }
     ]
    },
    {
     "title": "Most Disliked Video",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.id AS \"Video ID\",\n      video.title AS \"Video Title\", \n      MAX(dislikes) AS \"Dislikes\",\n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\"\n    FROM\n      video\n    GROUP BY video.id\n    ORDER BY MAX(dislikes) DESC\n    LIMIT 1\n  )\nSELECT \n  most.\"Video Title\", \n  most.\"Video ID\",\n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  most.\"Dislikes\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\""
      }
     ]
    },
    {
     "title": "Most Commented Video",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.id AS \"Video ID\",\n      video.title AS \"Video Title\", \n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\",\n      MAX(\"commentCount\") AS \"Comments\"\n    FROM\n      video\n    GROUP BY video.id\n    ORDER BY MAX(\"commentCount\") DESC\n    LIMIT 1\n  )\nSELECT \n  most.\"Video Title\", \n  most.\"Video ID\",\n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  most.\"Comments\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\""
      }
     ]
    }
   ]
  },
  { "title": "Per Year", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  $year AS \"Year\""
    },
    {
     "rawSql": "SELECT \n  SUM(\"videosPublished\") AS \"Videos Published\"\nFROM video_summary\nWHERE year = $year \nGROUP BY \"year\"\nORDER BY year  DESC"
    },
    {
     "rawSql": "SELECT\n  COUNT(*) AS \"Trends\"\nFROM trend\nWHERE \n  EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year"
    }
   ]
  },
  {
   "title": "Top Trending Occurrences Per Video",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "WITH most AS \n  (\n    SELECT\n      \"videoId\",\n      COUNT(*) AS \"Trends\"\n    FROM trend\n    WHERE \n      EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year\n    GROUP BY \"videoId\"\n    ORDER BY \"Trends\" DESC\n    LIMIT 10\n  )\nSELECT \n  video.title AS \"Video\",\n  most.\"Trends\"\nFROM \n  video, most\nWHERE \n  video.id = most.\"videoId\"\nORDER BY \"Trends\" DESC"
    }
   ]
  }
 ]
}