{
 "title": "Category",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "categoryId", "label": "Category ID", "query": "$categoryId" },
   {
    "name": "year",
    "label": "Year",
    "query": "select distinct \"year\" from trend_summary;"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  title \nFROM category \nWHERE id=$categoryId"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \n  id AS \"ID\", \n  title AS \"Title\" ,\n  assignable AS \"Assignable\",\n  etag AS \"eTag\"\nFROM category \nWHERE id=$categoryId"
    }
   ]
  },
  {
   "title": "Overall Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Categories, Channels and Videos",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  COUNT(DISTINCT \"channelId\") AS \"Channels\" \nFROM video \nWHERE video.\"categoryId\"='$categoryId'"
      },
      {
       "rawSql": "SELECT \n  SUM(\"videosPublished\") AS \"Videos\"\nFROM video_summary\nWHERE \"categoryId\"='$categoryId'"
      }
     ]
    },
    {
     "title": "Videos Published Per Year",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT \n  EXTRACT(YEAR FROM \"publishedAt\") AS \"Year\",\n  COUNT(*) AS \"Videos Published\"\nFROM video\nWHERE \"categoryId\"='$categoryId'\nGROUP BY \"Year\"\nORDER BY \"Year\"  DESC"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  SUM(\"viewCount\") AS \"Views\",\n  SUM(likes) AS \"Likes\",\n  SUM(dislikes) AS \"Dislikes\",\n  SUM(\"commentCount\") AS \"Comments\"\nFROM video_summary\nWHERE \"categoryId\" = '$categoryId'"
      }
     ]
    },
    {
     "title": "Views Per Day Of The Week",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT\n  \"dowPublished\" AS \"Day\",\n  SUM(\"viewCount\") AS \"Views 2020\"\nFROM video\nWHERE \n  EXTRACT(YEAR FROM \"publishedAt\" AT TIME ZONE 'UTC') = 2020\n  AND video.\"categoryId\"='$categoryId'\nGROUP BY \"Day\"\nORDER BY 1\n"
      },
      {
       "rawSql": "SELECT\n  \"dowPublished\" AS \"Day\",\n  SUM(\"viewCount\") AS \"Views 2021\"\nFROM video\nWHERE \n  EXTRACT(YEAR FROM \"publishedAt\" AT TIME ZONE 'UTC') = 2021\n  AND video.\"categoryId\"='$categoryId'\nGROUP BY \"Day\"\nORDER BY 1\n"
      },
      {
       "rawSql": "SELECT\n  \"dowPublished\" AS \"Day\",\n  SUM(\"viewCount\") AS \"Views 2022\"\nFROM video\nWHERE \n  EXTRACT(YEAR FROM \"publishedAt\" AT TIME ZONE 'UTC') = 2022\n  AND video.\"categoryId\"='$categoryId'\nGROUP BY \"Day\"\nORDER BY 1\n"
      },
      {
       "rawSql": "SELECT\n  \"dowPublished\" AS \"Day\",\n  SUM(\"viewCount\") AS \"Views 2023\"\nFROM video\nWHERE \n  EXTRACT(YEAR FROM \"publishedAt\" AT TIME ZONE 'UTC') = 2023\n  AND video.\"categoryId\"='$categoryId'\nGROUP BY \"Day\"\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Top Channels With Most Videos",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT \n  channel.title AS \"Channel\",\n  COUNT(*) AS \"Videos Published\"\nFROM video, channel\nWHERE \n  \"categoryId\"=$categoryId \n  AND \"channelId\"=channel.id\nGROUP BY \"Channel\"\nORDER BY \"Videos Published\"  DESC\nLIMIT 10"
      }
     ]
    },
    {
     "title": "Best Day Of The Week For Views",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  \"day\" AS \"Best Day For Views\",\n  AVG(\"ViewCount\") AS \"Total Views\"\nFROM (\nSELECT\n  \"dowPublished\" AS \"day\",\n  SUM(\"viewCount\") AS \"ViewCount\"\nFROM video\nWHERE \n  EXTRACT(YEAR FROM \"publishedAt\" AT TIME ZONE 'UTC') IN (2020,2021,2022,2023)\n  AND video.\"categoryId\"='$categoryId'\nGROUP BY \"day\"\nORDER BY 1\n) AS perDOWperYear\nGROUP BY \"day\"\nORDER BY \"Total Views\" DESC\nLIMIT 1"
      }
     ]
    },
    {
     "title": "Most Viewed Videos",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.title AS \"Video Title\", \n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\",\n      MAX(\"viewCount\") AS \"Views\"\n    FROM\n      video\n    WHERE \"categoryId\"='$categoryId'\n    GROUP BY video.id\n    ORDER BY MAX(\"viewCount\") DESC\n    LIMIT 3\n  )\nSELECT \n  most.\"Video Title\", \n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  category.id AS \"Category ID\",\n  most.\"Views\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\"\nORDER BY most.\"Views\" DESC"
      }
     ]
    },
    {
     "title": "Most Liked Videos",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.title AS \"Video Title\", \n      MAX(likes) AS \"Likes\",\n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\"\n    FROM\n      video\n    WHERE \"categoryId\"='$categoryId'\n    GROUP BY video.id\n    ORDER BY MAX(likes) DESC\n    LIMIT 3\n  )\nSELECT \n  most.\"Video Title\", \n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  category.id AS \"Category ID\",\n  most.\"Likes\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\"\nORDER BY most.\"Likes\" DESC"
      }
     ]
    },
    {
     "title": "Most Disliked Videos",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.title AS \"Video Title\", \n      MAX(dislikes) AS \"Dislikes\",\n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\"\n    FROM\n      video\n    WHERE \"categoryId\"='$categoryId'\n    GROUP BY video.id\n    ORDER BY MAX(dislikes) DESC\n    LIMIT 3\n  )\nSELECT \n  most.\"Video Title\", \n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  category.id AS \"Category ID\",\n  most.\"Dislikes\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\"\nORDER BY most.\"Dislikes\" DESC"
      }
     ]
    },
    {
     "title": "Most Commented Videos",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.title AS \"Video Title\", \n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\",\n      MAX(\"commentCount\") AS \"Comments\"\n    FROM\n      video\n    WHERE \"categoryId\"='$categoryId'\n    GROUP BY video.id\n    ORDER BY MAX(\"commentCount\") DESC\n    LIMIT 3\n  )\nSELECT \n  most.\"Video Title\", \n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  category.id AS \"Category ID\",\n  most.\"Comments\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\"\nORDER BY most.\"Comments\" DESC"
      }
     ]
    }
   ]
  },
  { "title": "Trends Per Year", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  $year AS \"Year\""
    },
    {
     "rawSql": "SELECT \n  SUM(\"videosPublished\") AS \"Videos Published\"\nFROM video_summary\nWHERE \n  year = $year \n  AND \"categoryId\"='$categoryId' \nGROUP BY \"year\""
    },
    {
     "rawSql": "SELECT\n  COUNT(*) AS \"Trends\"\nFROM trend\nWHERE \n  EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year\n  AND \"categoryId\"='$categoryId' "
    }
   ]
  },
  {
   "title": "Top Trending Occurrences Per Channel",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "WITH most AS \n  (\n    SELECT\n      \"channelId\",\n      COUNT(*) AS \"Trends\"\n    FROM trend\n    WHERE \n      \"categoryId\"='$categoryId' \n      AND EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year\n    GROUP BY \"channelId\"\n    ORDER BY \"Trends\" DESC\n    LIMIT 10\n  )\nSELECT \n  channel.title AS \"Channel\",\n  most.\"Trends\"\nFROM \n  channel, most\nWHERE \n  channel.id = most.\"channelId\"\nORDER BY \"Trends\" DESC"
    }
   ]
  },
  {
   "title": "Top Trending Occurrences Per Region",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"regionId\",\n  COUNT(*) AS \"Trends\"\nFROM trend\nWHERE \n  \"categoryId\"='$categoryId' \n  AND EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year\nGROUP BY \"regionId\"\nORDER BY \"Trends\" DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top Trending Occurrences Per Video",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "WITH most AS \n  (\n    SELECT\n      \"videoId\",\n      COUNT(*) AS \"Trends\"\n    FROM trend\n    WHERE \n      \"categoryId\"='$categoryId' \n      AND EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year\n    GROUP BY \"videoId\"\n    ORDER BY \"Trends\" DESC\n    LIMIT 10\n  )\nSELECT \n  video.title AS \"Video\",\n  most.\"Trends\"\nFROM \n  video, most\nWHERE \n  video.id = most.\"videoId\"\nORDER BY \"Trends\" DESC"
    }
   ]
  }
 ]
}