{
 "title": "Channel",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "channelId", "label": "Channel ID", "query": "$channelId" },
   {
    "name": "year",
    "label": "Year",
    "query": "select distinct \"year\" from trend_summary;"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  title \nFROM channel \nWHERE id='$channelId'"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \n  id AS \"ID\",\n  title AS \"Title\"\nFROM channel \nWHERE id='$channelId'"
    }
   ]
  },
  {
   "title": "Categories, and Videos",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"videosPublished\" AS \"Videos\"\nFROM channel \nWHERE \n  id='$channelId'"
    },
    {
     "rawSql": "SELECT \n  COUNT(DISTINCT \"categoryId\") AS \"Categories\" \nFROM video \nWHERE video.\"channelId\"='$channelId'"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  SUM(\"viewCount\") as \"Views\",\n  SUM(likes) as \"Likes\",\n  SUM(dislikes) as \"Dislikes\",\n  SUM(\"commentCount\") as \"Comments\"\nFROM video\nWHERE \"channelId\"='$channelId'"
    }
   ]
  },
  {
   "title": "Overall Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Videos Published Per Year",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT \n  EXTRACT(YEAR FROM \"publishedAt\") AS \"Year\",\n  COUNT(*) AS \"Videos Published\"\nFROM video\nWHERE \"channelId\"='$channelId'\nGROUP BY \"Year\"\nORDER BY \"Year\"  DESC"
      }
     ]
    },
    {
     "title": "Most Used Categories",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  max_freq,\n  category.title\nFROM into_values((SELECT mcv_agg(1, \"categoryId\") FROM video WHERE \"channelId\"='$channelId')) AS values\nJOIN category ON category.id = values.value\nORDER BY max_freq DESC\nLIMIT 3"
      }
     ]
    },
    {
     "title": "Most Viewed Categories",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.\"categoryId\",\n      SUM(\"viewCount\") AS \"Views\"\n    FROM video\n    WHERE \"channelId\"='$channelId'\n    GROUP BY video.\"categoryId\"\n    ORDER BY SUM(\"viewCount\") DESC\n    LIMIT 3\n  )\nSELECT \n  category.title AS \"Category\",\n  most.\"Views\"\nFROM \n  category, most\nWHERE \n  category.id = most.\"categoryId\"\nORDER BY most.\"Views\" DESC"
      }
     ]
    },
    {
     "title": "Most Viewed Videos",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.title AS \"Video Title\", \n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\",\n      MAX(\"viewCount\") AS \"Views\"\n    FROM\n      video\n    WHERE video.\"channelId\"='$channelId'\n    GROUP BY video.id\n    ORDER BY MAX(\"viewCount\") DESC\n    LIMIT 3\n  )\nSELECT \n  most.\"Video Title\", \n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  most.\"Views\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\"\nORDER BY most.\"Views\" DESC"
      }
     ]
    },
    {
     "title": "Most Liked Videos",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.title AS \"Video Title\", \n      MAX(likes) AS \"Likes\",\n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\"\n    FROM\n      video\n    WHERE video.\"channelId\"='$channelId'\n    GROUP BY video.id\n    ORDER BY MAX(likes) DESC\n    LIMIT 3\n  )\nSELECT \n  most.\"Video Title\", \n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  most.\"Likes\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\"\nORDER BY most.\"Likes\" DESC"
      }
     ]
    },
    {
     "title": "Most Disliked Videos",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.title AS \"Video Title\", \n      MAX(dislikes) AS \"Dislikes\",\n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\"\n    FROM\n      video\n    WHERE video.\"channelId\"='$channelId'\n    GROUP BY video.id\n    ORDER BY MAX(dislikes) DESC\n    LIMIT 3\n  )\nSELECT \n  most.\"Video Title\", \n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  most.\"Dislikes\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\"\nORDER BY most.\"Dislikes\" DESC"
      }
     ]
    },
    {
     "title": "Most Commented Videos",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "WITH most AS \n  (\n    SELECT\n      video.title AS \"Video Title\", \n      MAX(\"commentCount\") AS \"Comments\",\n      video.\"channelId\",\n      video.\"categoryId\" AS \"Category\"\n    FROM\n      video\n    WHERE video.\"channelId\"='$channelId'\n    GROUP BY video.id\n    ORDER BY MAX(\"commentCount\") DESC\n    LIMIT 3\n  )\nSELECT \n  most.\"Video Title\", \n  channel.title AS \"Channel\", \n  most.\"channelId\" AS \"Channel ID\",\n  category.title AS \"Category\",\n  most.\"Comments\"\nFROM \n  channel, most, category\nWHERE \n  channel.id = most.\"channelId\" \n  AND category.id = most.\"Category\"\nORDER BY most.\"Comments\" DESC"
      }
     ]
    }
   ]
  },
  { "title": "Trends Per Year", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  $year AS \"Year\""
    },
    {
     "rawSql": "SELECT \n  COUNT(*) AS \"Videos Published\"\nFROM video\nWHERE \n  EXTRACT(YEAR FROM \"publishedAt\") = $year\n  AND \"channelId\"='$channelId' "
    },
    {
     "rawSql": "SELECT\n  COUNT(*) AS \"Trends\"\nFROM trend\nWHERE \n  \"channelId\"='$channelId' \n  AND EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year"
    }
   ]
  },
  {
   "title": "Top Trending Occurrences Per Video",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "WITH most AS \n  (\n    SELECT\n      \"videoId\",\n      COUNT(*) AS \"Trends\"\n    FROM trend\n    WHERE \n      \"channelId\"='$channelId' \n      AND EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year\n    GROUP BY \"videoId\"\n    ORDER BY \"Trends\" DESC\n    LIMIT 10\n  )\nSELECT \n  video.title AS \"Video\",\n  most.\"Trends\"\nFROM \n  video, most\nWHERE \n  video.id = most.\"videoId\"\nORDER BY \"Trends\" DESC"
    }
   ]
  },
  { "title": "Trending Videos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Videos Published",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT  \n  title AS \"Video Title\",\n  EXTRACT(YEAR FROM \"publishedAt\" AT TIME ZONE 'UTC') AS \"Year\",\n  id AS \"Video ID\"\nFROM video\nWHERE\n  EXTRACT(YEAR FROM \"publishedAt\" AT TIME ZONE 'UTC') = $year\n  AND \"channelId\" = '$channelId'\nORDER BY \"publishedAt\" DESC"
    }
   ]
  }
 ]
}