{
 "title": "Region",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "regionId", "label": "Region ID", "query": "$regionId" },
   {
    "name": "year",
    "label": "Year",
    "query": "select distinct \"year\" from trend_summary;"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  name \nFROM region \nWHERE id='$regionId'"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \n  id AS \"Region Code\",\n  name AS \"Region Name\"\nFROM region\nWHERE region.id='$regionId'"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \n  id AS \"Region Code\",\n  name AS \"Region Name\"\nFROM region \nWHERE id='$regionId'"
    }
   ]
  },
  { "title": "Trends Per Year", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Trends",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  $year AS \"Year\""
    },
    {
     "rawSql": "SELECT\n  SUM(\"trendsCount\") AS \"Trends\"\nFROM trend_summary\nWHERE \n  year = $year \n  AND \"regionId\"='$regionId'"
    }
   ]
  },
  {
   "title": "Trend Counts Per Region",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  SUM(\"trendingVideos\") AS \"Videos\",\n  SUM(\"trendingChannels\") AS \"Channels\",\n  SUM(\"trendingCategories\") AS \"Categories\"\nFROM trend_summary\nWHERE \n  year = $year \n  AND \"regionId\" = '$regionId'\nORDER BY \"Videos\" DESC"
    }
   ]
  },
  {
   "title": "Top Trending Occurrences Per Category",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "WITH most AS \n  (\n    SELECT\n      \"categoryId\",\n      COUNT(*) AS \"Trends\"\n    FROM trend\n    WHERE \n      \"regionId\"='$regionId' \n      AND EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year\n    GROUP BY \"categoryId\"\n    ORDER BY \"Trends\" DESC\n    LIMIT 10\n  )\nSELECT \n  category.title AS \"Category\",\n  most.\"Trends\"\nFROM \n  category, most\nWHERE \n  category.id = most.\"categoryId\"\nORDER BY \"Trends\" DESC"
    }
   ]
  },
  {
   "title": "Top Trending Occurrences Per Channel",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "WITH most AS \n  (\n    SELECT\n      \"channelId\",\n      COUNT(*) AS \"Trends\"\n    FROM trend\n    WHERE \n      \"regionId\"='$regionId' \n      AND EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year\n    GROUP BY \"channelId\"\n    ORDER BY \"Trends\" DESC\n    LIMIT 10\n  )\nSELECT \n  channel.title AS \"Channel\",\n  most.\"Trends\"\nFROM \n  channel, most\nWHERE \n  channel.id = most.\"channelId\"\nORDER BY \"Trends\" DESC"
    }
   ]
  },
  {
   "title": "Top Trending Occurrences Per Video",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "WITH most AS \n  (\n    SELECT\n      \"videoId\",\n      COUNT(*) AS \"Trends\"\n    FROM trend\n    WHERE \n      \"regionId\"='$regionId' \n      AND EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year\n    GROUP BY \"videoId\"\n    ORDER BY \"Trends\" DESC\n    LIMIT 10\n  )\nSELECT \n  video.title AS \"Video\",\n  most.\"Trends\"\nFROM \n  video, most\nWHERE \n  video.id = most.\"videoId\"\nORDER BY \"Trends\" DESC"
    }
   ]
  }
 ]
}