{
 "title": "Video",
 "time": { "from": "2023-08-04T11:24:30.156Z", "to": "2023-09-12T18:59:09.518Z" },
 "templating": {
  "list": [
   { "name": "videoId", "label": "Video ID", "query": "$videoId" },
   {
    "name": "year",
    "label": "Year",
    "query": "select distinct \"year\" from trend_summary;"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  title \nFROM video  \nWHERE id='$videoId'"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \n  video.title AS \"Title\",\n  channel.title AS \"Channel\",\n  category.title AS \"Category\"\nFROM video\nJOIN channel ON channel.id = \"channelId\"\nJOIN category ON category.id = \"categoryId\"\nWHERE video.id='$videoId'"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \n  id AS \"Video ID\",\n  'Go To YouTube Video' AS \"Link To Video\",\n  \"publishedAt\" AS \"Published At\",\n  \"dowPublished\" AS \"Published On\",\n  \"commentsDisabled\" AS \"Comments Disabled\",\n  \"ratingsDisabled\" AS \"Ratings Disabled\"\nFROM video\nWHERE video.id='$videoId'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  description AS \"Video Description\"\nFROM video\nWHERE video.id='$videoId'"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"viewCount\" AS \"Views\",\n  likes AS \"Likes\",\n  dislikes AS \"Dislikes\",\n  \"commentCount\" AS \"Comments\"\nFROM video\nWHERE video.id='$videoId'"
    }
   ]
  },
  {
   "title": "Total Views",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT \n  \"trendingDate\", \n  \"viewCount\" AS \"Views\"\nFROM \n  trend \nWHERE \n  \"videoId\" = '$videoId' "
    }
   ]
  },
  {
   "title": "Total Likes, Dislikes and Comments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT \n  \"trendingDate\",\n  likes AS \"Likes\",\n  dislikes AS \"Dislikes\",\n  \"commentCount\" AS \"Comments\"\nFROM \n  trend \nWHERE \n  \"videoId\" = '$videoId'"
    }
   ]
  },
  { "title": "Trends Per Year", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Videos Published Per Year",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  $year AS \"Year\""
    },
    {
     "rawSql": "WITH most AS \n  (\n    SELECT\n      \"videoId\",\n      COUNT(*) AS \"Trends\"\n    FROM trend\n    WHERE \n      \"videoId\"='$videoId' \n      AND EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year\n    GROUP BY \"videoId\"\n    ORDER BY \"Trends\" DESC\n    LIMIT 10\n  )\nSELECT \n  most.\"Trends\"\nFROM \n  video, most\nWHERE \n  video.id = most.\"videoId\"\nORDER BY \"Trends\" DESC"
    }
   ]
  },
  {
   "title": "Views Per Year",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT \n  \"trendingDate\", \n  \"viewCount\" AS \"Views\"\nFROM \n  trend \nWHERE \n  \"videoId\" = '$videoId'\n  AND EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year"
    }
   ]
  },
  {
   "title": "Likes, Dislikes and Comments Per Year",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT \n  \"trendingDate\", \n  likes AS \"Likes\",\n  dislikes AS \"Dislikes\",\n  \"commentCount\" AS \"Comments\"\nFROM \n  trend \nWHERE \n  \"videoId\" = '$videoId'\n  AND EXTRACT(YEAR FROM \"trendingDate\" AT TIME ZONE 'UTC') = $year"
    }
   ]
  }
 ]
}