{
 "title": "Exploratory Data Analysis",
 "time": { "from": "2023-11-08T08:18:40.729Z", "to": "2023-11-08T20:18:40.729Z" },
 "panels": [
  {
   "title": "Counts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS \"Trends\" FROM trend"
    },
    {
     "rawSql": "SELECT COUNT(*) AS \"Regions\" FROM region"
    },
    {
     "rawSql": "SELECT COUNT(*) AS \"Categories\" FROM category"
    },
    {
     "rawSql": "SELECT COUNT(*) AS \"Channels\" FROM channel"
    },
    {
     "rawSql": "SELECT COUNT(*) AS \"Videos\" FROM video"
    }
   ]
  },
  {
   "title": "Trend Dates",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nMIN(\"trendingDate\") AS \"Earliest Trend Date\",\nMAX(\"trendingDate\") AS \"Latest Trend Date\"\nFROM trend"
    }
   ]
  },
  {
   "title": "Video Averages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nROUND(average(stats_agg(\"viewCount\"))) AS \"Views\",\nROUND(average(stats_agg(\"likes\"))) AS \"Likes\",\nROUND(average(stats_agg(\"dislikes\"))) AS \"Dislikes\",\nROUND(average(stats_agg(\"commentCount\"))) AS \"Comments\"\nFROM video"
    }
   ]
  },
  {
   "title": "Video Maximum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \ninto_values(max_n(\"viewCount\", 1)) AS \"Views\",\ninto_values(max_n(\"likes\", 1)) AS \"Likes\",\ninto_values(max_n(\"dislikes\", 1)) AS \"Dislikes\",\ninto_values(max_n(\"commentCount\", 1)) AS \"Comments\"\nFROM video"
    }
   ]
  },
  {
   "title": "Video Minimum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \ninto_values(min_n(\"viewCount\", 1)) AS \"Views\",\ninto_values(min_n(\"likes\", 1)) AS \"Likes\",\ninto_values(min_n(\"dislikes\", 1)) AS \"Dislikes\",\ninto_values(min_n(\"commentCount\", 1)) AS \"Comments\"\nFROM video"
    }
   ]
  },
  {
   "title": "Video Standard Deviation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nROUND(stddev(stats_agg(\"viewCount\"))) AS \"Views\",\nROUND(stddev(stats_agg(\"likes\"))) AS \"Likes\",\nROUND(stddev(stats_agg(\"dislikes\"))) AS \"Dislikes\",\nROUND(stddev(stats_agg(\"commentCount\"))) AS \"Comments\"\nFROM video"
    }
   ]
  },
  {
   "title": "Region",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "region schema",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "rawSql": "SELECT\n  table_name,\n  column_name,\n  data_type\nFROM\n  information_schema.columns\nWHERE\n  table_name='region'"
      }
     ]
    },
    {
     "title": "region (limit of 100 rows)",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "rawSql": "SELECT * FROM region ORDER BY id LIMIT 100;"
      }
     ]
    }
   ]
  },
  {
   "title": "Category",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "category schema",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "rawSql": "SELECT\n  table_name,\n  column_name,\n  data_type\nFROM\n  information_schema.columns\nWHERE\n  table_name='category'"
      }
     ]
    },
    {
     "title": "category (limit of 100 rows)",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "rawSql": "SELECT * FROM category ORDER BY id LIMIT 100;"
      }
     ]
    }
   ]
  },
  {
   "title": "Channel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "channel schema",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  table_name,\n  column_name,\n  data_type\nFROM\n  information_schema.columns\nWHERE\n  table_name='channel'"
      }
     ]
    },
    {
     "title": "channel (limit of 100 rows)",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT * FROM channel ORDER BY title LIMIT 100;"
      }
     ]
    }
   ]
  },
  {
   "title": "Video",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "video schema",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  table_name,\n  column_name,\n  data_type\nFROM\n  information_schema.columns\nWHERE\n  table_name='video'"
      }
     ]
    },
    {
     "title": "video (limit of 100 rows)",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT * FROM video ORDER BY title LIMIT 100;"
      }
     ]
    }
   ]
  },
  {
   "title": "Trend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "trend schema",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT\n  table_name,\n  column_name,\n  data_type\nFROM\n  information_schema.columns\nWHERE\n  table_name='trend'"
      }
     ]
    },
    {
     "title": "trend (limit of 100 rows)",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "rawSql": "SELECT * FROM trend ORDER BY \"trendingDate\" LIMIT 100;"
      }
     ]
    }
   ]
  },
  {
   "title": "Materialized Views",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "trend_summary",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT * FROM trend_summary ORDER BY year, \"regionId\";"
      }
     ]
    },
    {
     "title": "video_summary",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "rawSql": "SELECT * FROM video_summary ORDER BY year, \"categoryId\";"
      }
     ]
    }
   ]
  }
 ]
}